create table pet (
                     pet_id bigint generated by default as identity,
                     pet_cartao_vacinacao varchar(255),
                     end_bairro varchar(255) not null,
                     end_cep varchar(255),
                     end_cidade varchar(255) not null,
                     end_complemento varchar(255),
                     end_estado varchar(255) not null,
                     end_logradouro varchar(255) not null,
                     end_numero integer,
                     pet_especie varchar(255) not null check (pet_especie in ('CACHORRO','GATO')),
                     pet_idade integer not null check (pet_idade>=1),
                     pet_porte varchar(255) not null check (pet_porte in ('PEQUENO','MEDIO','GRANDE')),
                     pet_raca varchar(255) not null,
                     pet_status varchar(255) not null check (pet_status in ('ADOTADO','DISPONIVEL')),
                     primary key (pet_id)
);

alter table if exists pet
    add constraint UK_49g5yaxtwseuhcok2khdljgpb unique (pet_cartao_vacinacao);