create table pet (
                     pet_id bigint generated by default as identity,
                     pet_cartao_vacinacao varchar(255),
                     end_bairro varchar(255) not null,
                     end_cep varchar(255),
                     end_cidade varchar(255) not null,
                     end_complemento varchar(255),
                     end_estado varchar(255) not null,
                     end_logradouro varchar(255) not null,
                     end_numero integer,
                     pet_especie varchar(255) not null check (pet_especie in ('CACHORRO','GATO')),
                     pet_idade integer not null check (pet_idade>=1),
                     pet_nome varchar(255) not null,
                     pet_porte varchar(255) not null check (pet_porte in ('PEQUENO','MEDIO','GRANDE')),
                     pet_raca varchar(255) not null,
                     pet_status varchar(255) not null check (pet_status in ('ADOTADO','DISPONIVEL')),
                     usr_adotante_id bigint,
                     usr_doador_id bigint not null,
                     primary key (pet_id)
);

alter table if exists pet
    add constraint UK_49g5yaxtwseuhcok2khdljgpb unique (pet_cartao_vacinacao);


alter table if exists pet
    add constraint fk_usuario_adotante
        foreign key (usr_adotante_id)
            references usuario;

alter table if exists pet
    add constraint fk_usuario_doador
        foreign key (usr_doador_id)
            references usuario;


INSERT INTO pet (
    pet_cartao_vacinacao,
    end_bairro,
    end_cep,
    end_cidade,
    end_complemento,
    end_estado,
    end_logradouro,
    end_numero,
    pet_especie,
    pet_idade,
    pet_nome,
    pet_porte,
    pet_raca,
    pet_status,
    usr_adotante_id,
    usr_doador_id
) VALUES (
             '987654321',             -- pet_cartao_vacinacao
             'Jardim Paulista',       -- end_bairro
             '12345-678',             -- end_cep
             'São Paulo',             -- end_cidade
             'Apt 202',               -- end_complemento
             'SP',                    -- end_estado
             'Rua dos Gatos',         -- end_logradouro
             456,                     -- end_numero
             'GATO',                  -- pet_especie
             2,                       -- pet_idade
             'Mimi',                  -- pet_nome
             'PEQUENO',               -- pet_porte
             'Siamês',                -- pet_raca
             'DISPONIVEL',            -- pet_status
             NULL,                    -- usr_adotante_id (NULL porque o pet está disponível)
             1                        -- usr_doador_id (exemplo de ID do doador)
         );

INSERT INTO pet (
    pet_cartao_vacinacao,
    end_bairro,
    end_cep,
    end_cidade,
    end_complemento,
    end_estado,
    end_logradouro,
    end_numero,
    pet_especie,
    pet_idade,
    pet_nome,
    pet_porte,
    pet_raca,
    pet_status,
    usr_adotante_id,
    usr_doador_id
) VALUES (
             '987654311',             -- pet_cartao_vacinacao
             'Jardim Paulista',       -- end_bairro
             '12345-678',             -- end_cep
             'São Paulo',             -- end_cidade
             'Apt 202',               -- end_complemento
             'SP',                    -- end_estado
             'Rua dos Gatos',         -- end_logradouro
             456,                     -- end_numero
             'CACHORRO',                  -- pet_especie
             2,                       -- pet_idade
             'Mimi',                  -- pet_nome
             'PEQUENO',               -- pet_porte
             'Labrador',                -- pet_raca
             'DISPONIVEL',            -- pet_status
             NULL,                    -- usr_adotante_id (NULL porque o pet está disponível)
             1                        -- usr_doador_id (exemplo de ID do doador)
         );
